name: openat-frontend
static_sites:
  - name: openatfrontend
    dockerfile_path: Dockerfile
    github:
      branch: master
      deploy_on_push: true
      repo: openassistive/OpenATFrontEnd
    routes:
      - path: /
    source_dir: /
